CREATE TABLE contact(
	id			INT				NOT NULL AUTO_INCREMENT		COMMENT '主键',
	username	VARCHAR(64)		NOT NULL					COMMENT '用户名',
	email		VARCHAR(128)	NOT NULL					COMMENT '邮箱',
	content		BLOB			NOT NULL 					COMMENT '内容',
	createtime	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP	COMMENT '创建时间',
	modifytime	TIMESTAMP		DEFAULT CURRENT_TIMESTAMP	COMMENT '修改时间',
	PRIMARY KEY (id)
);