--  表名称--参数维护表
--  适用数据库：Mysql
--  表名称：PUB_APPPAR
--  字段前缀：APR
--  最后修改人：trojan
--  最后修改日期：2018.10.27

DROP TABLE IF EXISTS PUB_APPPAR;

CREATE TABLE PUB_APPPAR
(
	APR_NAME     	VARCHAR(60) 	NOT NULL COMMENT  '参数名称',
	APR_CODE     	VARCHAR(30) 	NOT NULL COMMENT '参数代码',
	APR_VALUE    	VARCHAR(40) 	NOT NULL COMMENT '参数值',
	APR_LANGUAGE 	VARCHAR(10) 	NOT NULL COMMENT '参数语种',
	APR_SHOWMSG  	VARCHAR(150)	NOT NULL COMMENT  '参数显示信息',
	APR_CLASS    	VARCHAR(6)	COMMENT  '参数类别，暂不使用',
	APR_SEQ      	INT		DEFAULT 0 	NOT NULL     COMMENT  '参数显示顺序',
	APR_FLAG     	VARCHAR(2)	DEFAULT '1'	NOT NULL   COMMENT  '参数渠道标志',
	PRIMARY  KEY (APR_CODE, APR_VALUE, APR_LANGUAGE)
)COMMENT='参数维护表';