CREATE TABLE USER(
  USERID    INT           AUTO_INCREMENT ,
  USERNAME  VARCHAR(32)   NOT NULL ,
  PASSWORD  VARCHAR(32)   NOT NULL,
  PRIMARY KEY (USERID)
);

INSERT INTO USER (USERNAME,PASSWORD) VALUES ('admin','123456');